import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createConnection } from '@playwright/mcp';
const log=(...a)=>console.log('[probe4]',...a);
const [ct,st]=InMemoryTransport.createLinkedPair();
const server=await createConnection({browser:{browserName:'chromium',launchOptions:{headless:true}},capabilities:['core']});
await server.connect(st);
const client=new Client({name:'p4',version:'0'},{capabilities:{}});
await client.connect(ct);
const sy=(s)=>(s.content||[]).filter(b=>b.type==='text').map(b=>b.text).join('\n');
await client.callTool({name:'browser_navigate',arguments:{url:'https://jobs.fortum.com/search/'}});
const snap=await client.callTool({name:'browser_snapshot',arguments:{}});
const yaml=sy(snap);
log('search snapshot len:',yaml.length);
log('--- first 2200 chars ---');
console.log(yaml.slice(0,2200));
log('total link refs:',(yaml.match(/- link [^\[]*\[ref=\w+\]/g)||[]).length);
log('cities:',[...new Set((yaml.match(/Helsinki|Espoo|Vantaa|Tampere|Stockholm|Oslo|Finland|Sweden|Norway|Remote/gi)||[]))].slice(0,15));
await client.close();process.exit(0);
